import { Message, MessageType, Notification } from "@/types";

export const notificationMockData: Notification[] = [
  {
    id: 1,
    title: "Tin Nhắn Mới",
    content: "John đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T09:00:00Z",
    type: "message",
    name: "Nhóm ae",
  },
  {
    id: 2,
    title: "Yêu Cầu Kết Bạn",
    content: "Anna đã gửi cho bạn một lời mời kết bạn.",
    isRead: false,
    timestamp: "2025-06-20T10:15:00Z",
    type: "friend_request",
    name: "John Doe",
  },
  {
    id: 3,
    title: "Lời Mời Tham Gia Nhóm",
    content: "Bạn đã được mời tham gia nhóm 'Project Team'.",
    isRead: true,
    timestamp: "2025-06-19T18:30:00Z",
    type: "group_invite",
    name: "Nhóm vui vẻ",
  },
  {
    id: 4,
    title: "Tin Nhắn Mới",
    content: "Lisa đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T11:00:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 5,
    title: "Thông Báo Hệ Thống",
    content: "Tài khoản của bạn đã được cập nhật.",
    isRead: true,
    timestamp: "2025-06-18T14:00:00Z",
    type: "system",
    name: "John Doe",
  },
  {
    id: 6,
    title: "Tin Nhắn Mới",
    content: "Mike đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T12:30:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 7,
    title: "Yêu Cầu Kết Bạn",
    content: "Chris đã gửi cho bạn một lời mời kết bạn.",
    isRead: true,
    timestamp: "2025-06-17T09:30:00Z",
    type: "friend_request",
    name: "John Doe",
  },
  {
    id: 8,
    title: "Lời Mời Tham Gia Nhóm",
    content: "Bạn đã được mời tham gia nhóm 'Gaming Squad'.",
    isRead: false,
    timestamp: "2025-06-16T20:00:00Z",
    type: "group_invite",
    name: "John Doe",
  },
  {
    id: 9,
    title: "Tin Nhắn Mới",
    content: "Emma đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T13:45:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 10,
    title: "Thông Báo Hệ Thống",
    content: "Có phiên bản ứng dụng mới sẵn sàng.",
    isRead: false,
    timestamp: "2025-06-15T07:00:00Z",
    type: "system",
    name: "John Doe",
  },
  {
    id: 11,
    title: "Tin Nhắn Mới",
    content: "David đã gửi cho bạn một tin nhắn.",
    isRead: true,
    timestamp: "2025-06-14T15:20:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 12,
    title: "Yêu Cầu Kết Bạn",
    content: "Sophia đã gửi cho bạn một lời mời kết bạn.",
    isRead: false,
    timestamp: "2025-06-20T14:10:00Z",
    type: "friend_request",
    name: "John Doe",
  },
  {
    id: 13,
    title: "Lời Mời Tham Gia Nhóm",
    content: "Bạn đã được mời tham gia nhóm 'Work Team'.",
    isRead: true,
    timestamp: "2025-06-13T11:00:00Z",
    type: "group_invite",
    name: "John Doe",
  },
  {
    id: 14,
    title: "Tin Nhắn Mới",
    content: "Oliver đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T14:30:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 15,
    title: "Thông Báo Hệ Thống",
    content: "Bạn đã đổi mật khẩu thành công.",
    isRead: true,
    timestamp: "2025-06-12T08:30:00Z",
    type: "system",
    name: "John Doe",
  },
  {
    id: 16,
    title: "Tin Nhắn Mới",
    content: "Mia đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T15:00:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 17,
    title: "Yêu Cầu Kết Bạn",
    content: "Lucas đã gửi cho bạn một lời mời kết bạn.",
    isRead: false,
    timestamp: "2025-06-11T10:45:00Z",
    type: "friend_request",
    name: "John Doe",
  },
  {
    id: 18,
    title: "Lời Mời Tham Gia Nhóm",
    content: "Bạn đã được mời tham gia nhóm 'Study Group'.",
    isRead: false,
    timestamp: "2025-06-10T16:00:00Z",
    type: "group_invite",
    name: "John Doe",
  },
  {
    id: 19,
    title: "Tin Nhắn Mới",
    content: "Ella đã gửi cho bạn một tin nhắn.",
    isRead: false,
    timestamp: "2025-06-20T15:30:00Z",
    type: "message",
    name: "John Doe",
  },
  {
    id: 20,
    title: "Thông Báo Hệ Thống",
    content: "Bảo trì hệ thống vào lúc 11 giờ tối nay.",
    isRead: false,
    timestamp: "2025-06-09T21:00:00Z",
    type: "system",
  },
];

export const getNotificationMockData = (): Promise<
  typeof notificationMockData
> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(notificationMockData);
    }, 2000);
  });
};

// conversationMockData.ts

export const conversationMockData: any[] = [
  {
    id: 1,
    name: "Nhóm bạn thân, anh em mình cứ thế thôi heheheeh",
    avatar: "https://i.pravatar.cc/150?img=1",
    lastMessage: "Hẹn gặp nhau cuối tuần nhé anh em mình cứ thế thôi!",
    lastMessageTime: "2025-06-09T10:30:00Z",
    unreadCount: 3,
    isGroup: true,
    isRead: false,
    createdAt: "2025-06-01T08:00:00Z",
    updatedAt: "2025-06-09T10:30:00Z",
  },
  {
    id: 2,
    name: "Minh",
    avatar: "https://i.pravatar.cc/150?img=2",
    lastMessage: "Đã gửi bạn tài liệu.",
    lastMessageTime: "2025-06-09T11:45:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-20T08:00:00Z",
    updatedAt: "2025-06-09T11:45:00Z",
  },
  {
    id: 3,
    name: "Phòng dự án",
    avatar: "https://i.pravatar.cc/150?img=3",
    lastMessage: "Nhớ nộp báo cáo trước thứ Sáu.",
    lastMessageTime: "2025-06-08T17:20:00Z",
    unreadCount: 5,
    isGroup: true,
    isRead: false,
    createdAt: "2025-06-01T09:00:00Z",
    updatedAt: "2025-06-08T17:20:00Z",
  },
  {
    id: 4,
    name: "Trâm",
    avatar: "https://i.pravatar.cc/150?img=4",
    lastMessage: "Gặp nhau lúc 7h nhé!",
    lastMessageTime: "2025-06-09T09:15:00Z",
    unreadCount: 1,
    isGroup: false,
    isRead: false,
    createdAt: "2025-05-30T10:00:00Z",
    updatedAt: "2025-06-09T09:15:00Z",
  },
  {
    id: 5,
    name: "Hùng",
    avatar: "https://i.pravatar.cc/150?img=5",
    lastMessage: "Ok bạn nhé!",
    lastMessageTime: "2025-06-07T15:30:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-25T10:00:00Z",
    updatedAt: "2025-06-07T15:30:00Z",
  },
  {
    id: 6,
    name: "Nhóm đá banh",
    avatar: "https://i.pravatar.cc/150?img=6",
    lastMessage: "Cuối tuần đá sân nào nhỉ?",
    lastMessageTime: "2025-06-06T18:00:00Z",
    unreadCount: 4,
    isGroup: true,
    isRead: false,
    createdAt: "2025-06-01T12:00:00Z",
    updatedAt: "2025-06-06T18:00:00Z",
  },
  {
    id: 7,
    name: "Lan",
    avatar: "https://i.pravatar.cc/150?img=7",
    lastMessage: "Gửi tớ link nhé.",
    lastMessageTime: "2025-06-05T14:00:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-28T11:00:00Z",
    updatedAt: "2025-06-05T14:00:00Z",
  },
  {
    id: 8,
    name: "Nhóm học tập",
    avatar: "https://i.pravatar.cc/150?img=8",
    lastMessage: "Bài tập deadline ngày mai nhé.",
    lastMessageTime: "2025-06-04T20:00:00Z",
    unreadCount: 2,
    isGroup: true,
    isRead: false,
    createdAt: "2025-06-01T13:00:00Z",
    updatedAt: "2025-06-04T20:00:00Z",
  },
  {
    id: 9,
    name: "Phương",
    avatar: "https://i.pravatar.cc/150?img=9",
    lastMessage: "Tối mai đi ăn nhé.",
    lastMessageTime: "2025-06-03T09:30:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-30T09:00:00Z",
    updatedAt: "2025-06-03T09:30:00Z",
  },
  {
    id: 10,
    name: "Nhóm gym",
    avatar: "https://i.pravatar.cc/150?img=10",
    lastMessage: "Hẹn tập 6h sáng mai.",
    lastMessageTime: "2025-06-02T06:00:00Z",
    unreadCount: 1,
    isGroup: true,
    isRead: false,
    createdAt: "2025-06-01T14:00:00Z",
    updatedAt: "2025-06-02T06:00:00Z",
  },
  {
    id: 11,
    name: "Thảo",
    avatar: "https://i.pravatar.cc/150?img=11",
    lastMessage: "Đi mua sách cùng không?",
    lastMessageTime: "2025-06-01T16:00:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-29T09:00:00Z",
    updatedAt: "2025-06-01T16:00:00Z",
  },
  {
    id: 12,
    name: "Nhóm phượt",
    avatar: "https://i.pravatar.cc/150?img=12",
    lastMessage: "Cuối tháng đi đâu đây?",
    lastMessageTime: "2025-05-31T19:00:00Z",
    unreadCount: 3,
    isGroup: true,
    isRead: false,
    createdAt: "2025-05-20T12:00:00Z",
    updatedAt: "2025-05-31T19:00:00Z",
  },
  {
    id: 13,
    name: "Tuấn",
    avatar: "https://i.pravatar.cc/150?img=13",
    lastMessage: "Mai cafe chứ?",
    lastMessageTime: "2025-05-30T08:30:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-21T10:00:00Z",
    updatedAt: "2025-05-30T08:30:00Z",
  },
  {
    id: 14,
    name: "Nhóm học tiếng Anh",
    avatar: "https://i.pravatar.cc/150?img=14",
    lastMessage: "Tối nay học Zoom nhé.",
    lastMessageTime: "2025-05-29T21:00:00Z",
    unreadCount: 2,
    isGroup: true,
    isRead: false,
    createdAt: "2025-05-15T11:00:00Z",
    updatedAt: "2025-05-29T21:00:00Z",
  },
  {
    id: 15,
    name: "Linh",
    avatar: "https://i.pravatar.cc/150?img=15",
    lastMessage: "Tớ gửi ảnh rồi đó.",
    lastMessageTime: "2025-05-28T15:00:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-10T10:00:00Z",
    updatedAt: "2025-05-28T15:00:00Z",
  },
  {
    id: 16,
    name: "Nhóm karaoke",
    avatar: "https://i.pravatar.cc/150?img=16",
    lastMessage: "Cuối tuần hát hò nhé.",
    lastMessageTime: "2025-05-27T20:00:00Z",
    unreadCount: 5,
    isGroup: true,
    isRead: false,
    createdAt: "2025-05-01T12:00:00Z",
    updatedAt: "2025-05-27T20:00:00Z",
  },
  {
    id: 17,
    name: "Dũng",
    avatar: "https://i.pravatar.cc/150?img=17",
    lastMessage: "Check giúp mình tài liệu.",
    lastMessageTime: "2025-05-26T10:00:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-15T09:00:00Z",
    updatedAt: "2025-05-26T10:00:00Z",
  },
  {
    id: 18,
    name: "Nhóm bóng rổ",
    avatar: "https://i.pravatar.cc/150?img=18",
    lastMessage: "Tập chiều nay 5h nhé.",
    lastMessageTime: "2025-05-25T17:00:00Z",
    unreadCount: 2,
    isGroup: true,
    isRead: false,
    createdAt: "2025-05-10T14:00:00Z",
    updatedAt: "2025-05-25T17:00:00Z",
  },
  {
    id: 19,
    name: "Vy",
    avatar: "https://i.pravatar.cc/150?img=19",
    lastMessage: "Bạn ơi có rảnh không?",
    lastMessageTime: "2025-05-24T08:00:00Z",
    unreadCount: 0,
    isGroup: false,
    isRead: true,
    createdAt: "2025-05-12T11:00:00Z",
    updatedAt: "2025-05-24T08:00:00Z",
  },
  {
    id: 20,
    name: "Nhóm chơi game",
    avatar: "https://i.pravatar.cc/150?img=20",
    lastMessage: "Tối nay chiến tiếp không?",
    lastMessageTime: "2025-05-23T21:30:00Z",
    unreadCount: 4,
    isGroup: true,
    isRead: false,
    createdAt: "2025-05-05T12:00:00Z",
    updatedAt: "2025-05-23T21:30:00Z",
  },
];

export const users = [
  {
    name: "Steve E.",
    username: "@steveEberger",
    avatar: "https://i.pravatar.cc/150?u=1",
    online: true,
  },
  {
    name: "Katherine Moss",
    username: "@kathy",
    avatar: "https://i.pravatar.cc/150?u=2",
    online: false,
  },
  {
    name: "Phoenix Baker",
    username: "@phoenix",
    avatar: "https://i.pravatar.cc/150?u=3",
    online: true,
  },
  {
    name: "Eleanor Pena",
    username: "@eleanor",
    avatar: "https://i.pravatar.cc/150?u=4",
    online: false,
  },
  {
    name: "Kenny Peterson",
    username: "@kenny",
    avatar: "https://i.pravatar.cc/150?u=5",
    online: true,
  },
  {
    name: "Al Sanders",
    username: "@al",
    avatar: "https://i.pravatar.cc/150?u=6",
    online: true,
  },
  {
    name: "Melissa Van Der Berg",
    username: "@melissa",
    avatar: "https://i.pravatar.cc/150?u=7",
    online: false,
  },
];

export const chatsMockData: Partial<Message>[] = [
  {
    id: "1",
    createdAt: "Wednesday 9:00am",
    updatedAt: "Wednesday 9:00am",
    deletedAt: null,
    content: "Hi Olivia, I am currently working on the project.",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "2",
    createdAt: "Wednesday 9:10am",
    updatedAt: "Wednesday 9:10am",
    deletedAt: null,
    content: "That sounds great, Mabel! Keep up the good work.",
    senderId: "you",
    type: MessageType.TEXT,
  },
  {
    id: "3",
    createdAt: "Wednesday 11:30am",
    updatedAt: "Wednesday 11:30am",
    deletedAt: null,
    content: "I will send the draft by end of the day.",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "4",
    createdAt: "Wednesday 2:00pm",
    updatedAt: "Wednesday 2:00pm",
    deletedAt: null,
    content: "Sure, I will be waiting for it.",
    senderId: "you",
    type: MessageType.TEXT,
  },
  {
    id: "5",
    createdAt: "Wednesday 4:30pm",
    updatedAt: "Wednesday 4:30pm",
    deletedAt: null,
    content: "Just a heads up, I am about to send the draft.",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "6",
    createdAt: "Thursday 10:16am",
    updatedAt: "Thursday 10:16am",
    deletedAt: null,
    content:
      "Thanks Olivia! Almost there. I'll work on making those changes you suggested and will shoot it over.",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "7",
    createdAt: "Thursday 11:40am",
    updatedAt: "Thursday 11:40am",
    deletedAt: null,
    content:
      "Hey Olivia, I've finished with the requirements doc! I made some notes in the gdoc as well for Phoenix to look over.",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "8",
    createdAt: "Thursday 11:40am",
    updatedAt: "Thursday 11:40am",
    deletedAt: null,
    content: "Tech requirements.pdf",
    senderId: "@steveEberger",
    type: MessageType.FILE,
  },
  {
    id: "9",
    createdAt: "Thursday 11:41am",
    updatedAt: "Thursday 11:41am",
    deletedAt: null,
    content: "Awesome! Thanks. I'll look at this today.",
    senderId: "you",
    type: MessageType.TEXT,
  },
  {
    id: "10",
    createdAt: "Thursday 11:44am",
    updatedAt: "Thursday 11:44am",
    deletedAt: null,
    content: "No rush though — we still have to wait for Lana's designs.",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "11",
    createdAt: "Today 2:20pm",
    updatedAt: "Today 2:20pm",
    deletedAt: null,
    content:
      "Hey Olivia, can you please review the latest design when you can?",
    senderId: "@steveEberger",
    type: MessageType.TEXT,
  },
  {
    id: "12",
    createdAt: "Just now",
    updatedAt: "Just now",
    deletedAt: null,
    content: "Sure thing, I'll have a look today. They're looking great!",
    senderId: "you",
    type: MessageType.TEXT,
  },
];
